using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Diamond.Tests
{
    public class DiamondTestData : IEnumerable<object[]>
    {
        private string YDiamond = "                        A                        \n                       B B                       \n                      C   C                      \n                     D     D                     \n                    E       E                    \n                   F         F                   \n                  G           G                  \n                 H             H                 \n                I               I                \n               J                 J               \n              K                   K              \n             L                     L             \n            M                       M            \n           N                         N           \n          O                           O          \n         P                             P         \n        Q                               Q        \n       R                                 R       \n      S                                   S      \n     T                                     T     \n    U                                       U    \n   V                                         V   \n  W                                           W  \n X                                             X \nY                                               Y\n X                                             X \n  W                                           W  \n   V                                         V   \n    U                                       U    \n     T                                     T     \n      S                                   S      \n       R                                 R       \n        Q                               Q        \n         P                             P         \n          O                           O          \n           N                         N           \n            M                       M            \n             L                     L             \n              K                   K              \n               J                 J               \n                I               I                \n                 H             H                 \n                  G           G                  \n                   F         F                   \n                    E       E                    \n                     D     D                     \n                      C   C                      \n                       B B                       \n                        A                        ";
        private string zDiamond = "                         A                         \n                        B B                        \n                       C   C                       \n                      D     D                      \n                     E       E                     \n                    F         F                    \n                   G           G                   \n                  H             H                  \n                 I               I                 \n                J                 J                \n               K                   K               \n              L                     L              \n             M                       M             \n            N                         N            \n           O                           O           \n          P                             P          \n         Q                               Q         \n        R                                 R        \n       S                                   S       \n      T                                     T      \n     U                                       U     \n    V                                         V    \n   W                                           W   \n  X                                             X  \n Y                                               Y \nZ                                                 Z\n Y                                               Y \n  X                                             X  \n   W                                           W   \n    V                                         V    \n     U                                       U     \n      T                                     T      \n       S                                   S       \n        R                                 R        \n         Q                               Q         \n          P                             P          \n           O                           O           \n            N                         N            \n             M                       M             \n              L                     L              \n               K                   K               \n                J                 J                \n                 I               I                 \n                  H             H                  \n                   G           G                   \n                    F         F                    \n                     E       E                     \n                      D     D                      \n                       C   C                       \n                        B B                        \n                         A                         ";
        private string QDiamond = "                A                \n               B B               \n              C   C              \n             D     D             \n            E       E            \n           F         F           \n          G           G          \n         H             H         \n        I               I        \n       J                 J       \n      K                   K      \n     L                     L     \n    M                       M    \n   N                         N   \n  O                           O  \n P                             P \nQ                               Q\n P                             P \n  O                           O  \n   N                         N   \n    M                       M    \n     L                     L     \n      K                   K      \n       J                 J       \n        I               I        \n         H             H         \n          G           G          \n           F         F           \n            E       E            \n             D     D             \n              C   C              \n               B B               \n                A                ";
        public IEnumerator<object[]> GetEnumerator()
        {
            yield return new object[] { 'A', "A" };
            yield return new object[] { 'B', " A \nB B\n A "};
            yield return new object[] { 'Y', YDiamond };
            yield return new object[] { 'z', zDiamond };
            yield return new object[] { 'Q', QDiamond };
        }

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }
}
